---

# Configure RabbitMQ

- name: 'BASH | Enable RABBITMQ Server Restartd.'
  systemd:
      name: "rabbitmq-server"
      state: stopped

- name: create rabbit directory
  command: mkdir -p /etc/rabbitmq/rabbitmq/
 
- name: default settings for RabbitMQ AMQP server
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq/rabbitmq-env.conf
    owner: root
    group: root
    mode: 0644

- name: Symlink RabbitMQ bin to sbin(for install plugins)
  file:
    src: /usr/lib/rabbitmq/bin
    dest: /usr/lib/rabbitmq/sbin
    state: link

- name: Enable the plugins is installed
  rabbitmq_plugin:
    names: "{{ item }}"
    prefix: /usr/lib/rabbitmq
    state: enabled
    new_only: yes
  with_items: "{{ rabbitmq_plugins }}"

- name: 'BASH | Enable RABBITMQ Server Restartd.'
  systemd:
      name: "rabbitmq-server"
      state: restarted
